import type { ProjectFile } from "./contracts.js";
export function projectTemplate(title: string): ProjectFile[] {
  return [
    { path: "package.json", content: JSON.stringify({ name: "harness-cloud-app", private: true, type: "module",
      scripts: { build: "vite build", check: "tsc --noEmit", start: "tsx server.ts" },
      dependencies: { react: "19.1.1", "react-dom": "19.1.1", vite: "7.1.5", typescript: "5.9.2", tsx: "4.20.5",
        "@types/react": "19.1.13", "@types/react-dom": "19.1.9", "@types/node": "22.18.6" } }, null, 2) },
    { path: "tsconfig.json", content: JSON.stringify({ compilerOptions: { target: "ES2022", module: "ESNext", moduleResolution: "Bundler",
      jsx: "react-jsx", strict: true, skipLibCheck: true, noEmit: true, allowJs: true }, include: ["src", "server.ts"] }, null, 2) },
    { path: "index.html", content: '<!doctype html><html lang="zh-CN"><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>' + title.replace(/[<>&"]/gu, "") + '</title><div id="root"></div><script type="module" src="/src/main.tsx"></script></html>' },
    { path: "server.ts", content: '// Extend the app with routes; infrastructure credentials never enter this file.\nimport { startApp } from "/opt/harness/runtime.mjs";\nstartApp({});\n' },
    { path: "src/main.tsx", content: 'import React, {useEffect,useState} from "react";\nimport {createRoot} from "react-dom/client";\nimport "./style.css";\n' +
      'async function api(path:string,body?:unknown){const r=await fetch("/api/"+path,{method:body?"POST":"GET",headers:{"Content-Type":"application/json"},...(body?{body:JSON.stringify(body)}:{})});const v=await r.json();if(!r.ok)throw new Error(v.error||"请求未完成");return v;}\n' +
      'function App(){const[user,setUser]=useState<{email:string}|null>(null);const[error,setError]=useState("");const[items,setItems]=useState<{id:string;data:{text:string}}[]>([]);async function load(){try{setUser((await api("auth/me")).user);setItems((await api("data/entries")).items)}catch{setUser(null)}}useEffect(()=>{void load()},[]);return <main><h1>{' + JSON.stringify(title) + '}</h1>{error&&<p role="alert">{error}</p>}{!user?<form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await api("auth/"+f.get("action"),{email:f.get("email"),password:f.get("password")});await load()}catch(x){setError(String(x))}}}><input name="email" type="email" placeholder="邮箱" required/><input name="password" type="password" minLength={10} placeholder="密码（至少10位）" required/><select name="action"><option value="login">登录</option><option value="register">注册</option></select><button>继续</button></form>:<><p>{user.email}</p><form onSubmit={async e=>{e.preventDefault();const form=e.currentTarget;try{await api("data/entries",{text:new FormData(form).get("text")});form.reset();await load()}catch(x){setError(String(x))}}}><input name="text" placeholder="记录内容" required/><button>保存</button></form><ul>{items.map(i=><li key={i.id}>{i.data.text}</li>)}</ul><label>上传文件<input type="file" onChange={async e=>{const f=e.target.files?.[0];if(!f)return;try{const data=await new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(",")[1]!);r.onerror=reject;r.readAsDataURL(f)});const result=await api("uploads",{name:f.name,data});setError("上传成功："+result.name)}catch(x){setError(String(x))}}}/></label><button onClick={async()=>{await api("auth/logout",{});setUser(null)}}>退出登录</button></>}</main>};\ncreateRoot(document.getElementById("root")!).render(<App/>);\n' },
    { path: "src/style.css", content: 'body{margin:0;background:#f6f7fb;color:#202636;font:14px/1.6 system-ui,sans-serif}main{max-width:760px;margin:40px auto;padding:24px;background:white;border:1px solid #e5e7eb;border-radius:16px}h1{font-size:24px}form{display:flex;gap:10px;flex-wrap:wrap;margin:20px 0}input,select,button{font:inherit;padding:10px 14px;border:1px solid #d1d5db;border-radius:8px}button{background:#315bdf;color:white;cursor:pointer}label{display:block}input{max-width:100%;box-sizing:border-box}li{padding:10px;border-bottom:1px solid #eee}@media(max-width:600px){main{margin:12px;padding:16px}form>*{width:100%}}\n' },
    { path: "README.md", content: "# " + title + "\n\nReact/Vite frontend and TypeScript backend. The runtime supplies /api/auth/register, /api/auth/login, /api/auth/me, /api/auth/logout, /api/data/:collection (GET/POST), /api/data/:collection/:id (GET/PUT/DELETE), /api/uploads (POST), /api/uploads/:id (GET). Built-in data and uploads require website login and are scoped to the website user. Development and production data are separate. Backend custom routes can use the trusted runtime broker for public HTTPS integration. Database credentials never belong in source.\n" }
  ];
}
